#!/usr/bin/env node
/**
 * PL Studio - Minimal CLI for Lambda Control
 * Speed, Proof, Mirror commands with zero friction
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load lattice control
const LATTICE_CONTROL = path.join(__dirname, '../fractal-lattice/lattice-control.js');

/**
 * Speed command - Analyze repository performance
 */
function speedCommand(repo) {
  console.log(`\n⚡ SPEED ANALYSIS: ${repo}\n`);
  console.log('=' .repeat(60));

  // Find test command
  const pkgPath = path.join(repo, 'package.json');
  if (!fs.existsSync(pkgPath)) {
    console.error('❌ No package.json found');
    return;
  }

  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
  const testCmd = pkg.scripts?.test || 'npm test';

  console.log(`Test command: ${testCmd}`);

  // Run baseline (3 times)
  console.log('\nRunning baseline (3x)...');
  const baselineTimes = [];
  for (let i = 0; i < 3; i++) {
    const start = Date.now();
    try {
      execSync(testCmd, { cwd: repo, stdio: 'ignore' });
    } catch (e) {
      // Tests might fail, we only care about timing
    }
    const time = Date.now() - start;
    baselineTimes.push(time);
    console.log(`  Run ${i + 1}: ${time}ms`);
  }

  const baselineMedian = baselineTimes.sort((a, b) => a - b)[1];

  // Generate receipt
  const receipt = {
    timestamp: new Date().toISOString(),
    repo: path.basename(repo),
    command: testCmd,
    baseline_ms: baselineMedian,
    attributes: [
      'type:validation',
      'exec:success',
      'oracle:no_fs',
      'oracle:no_net',
      'oracle:no_env',
      'size:m_1_10mb',
      'speed:medium'
    ]
  };

  // Get lattice decision
  const { decide } = require(LATTICE_CONTROL);
  const decision = decide(receipt.attributes);

  receipt.policy_decision = decision;
  receipt.estimated_speedup = decision.profile === 'apex' ? '3-5x' :
                              decision.profile === 'proof' ? '2-3x' :
                              decision.profile === 'performance' ? '1.5-2x' : '1x';

  // Save report
  const reportDir = path.join(repo, 'pl-reports');
  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }

  const reportPath = path.join(reportDir, `speed-${Date.now()}.json`);
  fs.writeFileSync(reportPath, JSON.stringify(receipt, null, 2));

  // Generate markdown
  const markdown = `# Speed Analysis Report

**Repository**: ${receipt.repo}
**Command**: \`${receipt.command}\`
**Baseline**: ${receipt.baseline_ms}ms

## Lattice Decision

- **Profile**: ${decision.profile}
- **Confidence**: ${decision.confidence.toFixed(2)}
- **Estimated Speedup**: ${receipt.estimated_speedup}
- **Genes**: MEMO=${decision.genes.MEMO}, PAR=${decision.genes.PAR}

## Recommendations

${decision.profile === 'apex' ? '✅ Maximum acceleration available - pure computation detected' :
  decision.profile === 'proof' ? '✅ Safe memoization available - no side effects detected' :
  decision.profile === 'performance' ? '⚡ Parallel processing recommended for large data' :
  '⚠️ Conservative mode - side effects or low confidence'}

---
*Generated by PL Studio*`;

  const mdPath = path.join(reportDir, 'speed-report.md');
  fs.writeFileSync(mdPath, markdown);

  console.log('\n📊 Results:');
  console.log(`  Baseline: ${baselineMedian}ms`);
  console.log(`  Profile: ${decision.profile}`);
  console.log(`  Speedup: ${receipt.estimated_speedup}`);
  console.log(`  Report: ${mdPath}`);
  console.log('=' .repeat(60));
}

/**
 * Proof command - Generate proof receipt for command
 */
function proofCommand(cmd) {
  console.log(`\n🔒 PROOF GENERATION: ${cmd}\n`);
  console.log('=' .repeat(60));

  // Execute command and capture
  const start = Date.now();
  let exitCode = 0;
  let stdout = '';
  let stderr = '';

  try {
    stdout = execSync(cmd, { encoding: 'utf-8' });
  } catch (e) {
    exitCode = e.status || 1;
    stderr = e.stderr?.toString() || '';
  }

  const duration = Date.now() - start;

  // Generate receipt
  const receipt = {
    timestamp: new Date().toISOString(),
    command: cmd,
    duration_ms: duration,
    exit_code: exitCode,
    attributes: []
  };

  // Analyze for oracles
  const hasFs = cmd.includes('fs') || cmd.includes('file') || cmd.includes('cat');
  const hasNet = cmd.includes('curl') || cmd.includes('wget') || cmd.includes('http');
  const hasEnv = cmd.includes('$') || cmd.includes('env');

  // Build attributes
  receipt.attributes.push(exitCode === 0 ? 'exec:success' : 'exec:failure');
  receipt.attributes.push(hasFs ? 'oracle:fs' : 'oracle:no_fs');
  receipt.attributes.push(hasNet ? 'oracle:net' : 'oracle:no_net');
  receipt.attributes.push(hasEnv ? 'oracle:env' : 'oracle:no_env');
  receipt.attributes.push(duration < 100 ? 'speed:fast' : duration < 1000 ? 'speed:medium' : 'speed:slow');

  // Get lattice decision
  const { decide } = require(LATTICE_CONTROL);
  const decision = decide(receipt.attributes);

  receipt.policy_decision = decision;
  receipt.proof = {
    deterministic: !hasFs && !hasNet && !hasEnv && exitCode === 0,
    memoization_safe: decision.genes.MEMO,
    side_effects: hasFs || hasNet || hasEnv
  };

  // Save receipt
  const receiptPath = `receipt-${Date.now()}.json`;
  fs.writeFileSync(receiptPath, JSON.stringify(receipt, null, 2));

  console.log('📝 Receipt generated:');
  console.log(`  Command: ${cmd}`);
  console.log(`  Duration: ${duration}ms`);
  console.log(`  Exit code: ${exitCode}`);
  console.log(`  Deterministic: ${receipt.proof.deterministic ? '✅' : '❌'}`);
  console.log(`  Memoizable: ${receipt.proof.memoization_safe ? '✅' : '❌'}`);
  console.log(`  Profile: ${decision.profile}`);
  console.log(`  Saved: ${receiptPath}`);
  console.log('=' .repeat(60));
}

/**
 * Mirror command - Generate lattice visualization
 */
function mirrorCommand(repo) {
  console.log(`\n🔮 MIRROR GENERATION: ${repo}\n`);
  console.log('=' .repeat(60));

  // Load lattice
  const latticePath = path.join(__dirname, '../fractal-lattice/lattice.json');
  const lattice = JSON.parse(fs.readFileSync(latticePath, 'utf-8'));

  console.log(`Lattice loaded:`);
  console.log(`  Concepts: ${lattice.concepts.length}`);
  console.log(`  Edges: ${lattice.edges.length}`);

  // Copy lattice visualization
  const svgSource = path.join(__dirname, '../fractal-lattice/lattice.svg');
  const svgDest = path.join(repo, 'lattice-mirror.svg');

  if (fs.existsSync(svgSource)) {
    fs.copyFileSync(svgSource, svgDest);
    console.log(`  SVG: ${svgDest}`);
  }

  // Generate snapshot report
  const snapshot = {
    timestamp: new Date().toISOString(),
    repo: path.basename(repo),
    lattice_version: '1.0.0',
    stats: {
      concepts: lattice.concepts.length,
      edges: lattice.edges.length,
      stability: 'J=1.0'
    },
    profiles: ['apex', 'proof', 'performance', 'universal'],
    visualization: 'lattice-mirror.svg'
  };

  const snapshotPath = path.join(repo, 'lattice-snapshot.json');
  fs.writeFileSync(snapshotPath, JSON.stringify(snapshot, null, 2));

  console.log(`  Snapshot: ${snapshotPath}`);
  console.log('\n✅ Mirror generated');
  console.log('=' .repeat(60));
}

/**
 * Main CLI
 */
function main() {
  const args = process.argv.slice(2);
  const command = args[0];
  const target = args[1];

  if (!command) {
    console.log('⚡ PL STUDIO - Lambda Control CLI\n');
    console.log('Commands:');
    console.log('  pl speed <repo>     - Analyze repository performance');
    console.log('  pl proof "<cmd>"    - Generate proof receipt for command');
    console.log('  pl mirror <repo>    - Generate lattice visualization');
    console.log('\nExamples:');
    console.log('  pl speed ./my-project');
    console.log('  pl proof "npm test"');
    console.log('  pl mirror .');
    return;
  }

  switch (command) {
    case 'speed':
      if (!target) {
        console.error('Usage: pl speed <repo>');
        process.exit(1);
      }
      speedCommand(target);
      break;

    case 'proof':
      if (!target) {
        console.error('Usage: pl proof "<command>"');
        process.exit(1);
      }
      proofCommand(target);
      break;

    case 'mirror':
      if (!target) {
        console.error('Usage: pl mirror <repo>');
        process.exit(1);
      }
      mirrorCommand(target);
      break;

    default:
      console.error(`Unknown command: ${command}`);
      process.exit(1);
  }
}

// Run
main();