[package]
name = "lambda-unikernel"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-core = { path = "../core" }
bootloader = "0.9"

[features]
default = []

[profile.release]
panic = "abort"